Debug tailscale

diff --git a/.github/workflows/HackerNews-DIYgest.yml b/.github/workflows/HackerNews-DIYgest.yml
--- a/.github/workflows/HackerNews-DIYgest.yml
+++ b/.github/workflows/HackerNews-DIYgest.yml
@@ -63,11 +63,29 @@ jobs:
 #           timeout-minutes: 1
 #           limit-access-to-actor: true
 
+      - name: Debug Secrets
+        run: |
+          echo "Checking TS_OAUTH_CLIENT_ID"
+          if [ -z "${{ secrets.TS_OAUTH_CLIENT_ID }}" ]; then
+            echo "::error::TS_OAUTH_CLIENT_ID is empty"
+            exit 1
+          else
+            echo "TS_OAUTH_CLIENT_ID is set"
+          fi
+          echo "Checking TS_OAUTH_SECRET"
+          if [ -z "${{ secrets.TS_OAUTH_SECRET }}" ]; then
+            echo "::error::TS_OAUTH_SECRET is empty"
+            exit 1
+          else
+            echo "TS_OAUTH_SECRET is set"
+          fi
+
       - name: Tailscale
         uses: tailscale/github-action@v2
         with:
           oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
           oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
+          tags: tag:cicd
 
       - name: Scrape
         run: bin/hn-hourly-scrape-pg.py
